### ISSUE TITLE
New SDK Design

### ISSUE THREAD

**Issue by git-hulk** [bitleak/go-lmstfy-client#1]
as https://github.com/bitleak/lmstfy/issues/111 mentioned, we want to make the client was easier for users.

## on the publishing side

the producer was simple enough that use `client.Publish(...)` to create a new task, so it's ok to keep the present state now.

## on the consuming side

we want to offer a high-level way to consume the task like below:

```
consumerConfig := &consumer.Config {
    Addr: "xxx",
    Token: "xx",
    Queues: []{"q1", "q2", "q3"},
    Timeout: 3 * time.Second,
}

consumer := NewConsumer(consumerConfig)
consumer.Receive(func(ctx context.Context, job *Job) error {
     // handle your job here
     job.Ack()
})

```

**Comment by git-hulk** [comment]
cc @henrylinnn, I'll migrate the old client first today.

**Comment by henrylinnn** [comment]
@git-hulk I have already created a pull request.Hope to see your advice.

**Comment by git-hulk** [comment]
Many thanks to @henrylinnn, I would have a look later and comment if has any thoughts 👍
